Feature/running tests in pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,22 +1,31 @@
-build-job:
+stages:
+  - build
+  - deploy
+
+Build:
   stage: build
+  image: gradle:8.8.0-alpine
   script:
-    - echo "Hello, $GITLAB_USER_LOGIN!"
+    - gradle --build-cache clean build --info --stacktrace || {
+      echo "Tests failed. Displaying test report logs:";
+      for file in build/test-results/test/*.xml; do
+      echo "----- $file -----";
+      cat "$file";
+      done;
+      exit 1;
+      }
+  artifacts:
+    when: always
+    expire_in: 1 days
+    paths:
+      - build/libs/*.jar
+      - build/test-results/test/*.xml
+    reports:
+      junit:
+        - build/test-results/test/*.xml
 
-test-job1:
-  stage: test
-  script:
-    - echo "This job tests something"
 
-test-job2:
-  stage: test
-  script:
-    - echo "This job tests something, but takes more time than test-job1."
-    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
-    - echo "which simulates a test that runs 20 seconds longer than test-job1"
-    - sleep 20
-
-deploy-prod:
+Deploy:
   stage: deploy
   script:
     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
